Repository YNVSolutions/SwiftCause_Web, pull requests merged in 2025-04, with the labels that each got.

#22 Main page component
  app/Components/Others/About.jsx
  app/Components/Others/Features.jsx
  app/Components/Others/LearnMore.jsx
  app/Components/Others/Main.jsx
  app/Components/Others/NavBar.jsx
  app/Components/Others/Sample.tsx
  app/page.tsx
  package-lock.json
  package.json
  public/head_image.png
Labels: enhancement, Component, Feature, UI UX

#24 Updating UI Of the main page
  app/Components/Others/Features.jsx
  app/Components/Others/Footer.jsx
  app/Components/Others/Main.jsx
  app/Components/Others/NavBar.jsx
  app/page.tsx
  package-lock.json
  package.json
  public/Camp_setup.png
  public/Flex_Donation_mode.png
  public/Integrated_Comm.png
  public/Real_Time_Funds.png
  public/gift_aid.png
  public/mobile_pay.png
Labels: enhancement, Component, Feature, UI UX

#25 Firebase UI integration
  app/Components/Auth/Login.jsx
  app/Components/Auth/SignIn.jsx
  app/Components/Auth/firebase.tsx
  app/page.tsx
  package-lock.json
  package.json
Labels: Component, Feature, Backend, DataBase

#30 Adding some more analytics to the user dashboard
  app/Components/Dashboard/Others/Details.jsx
  app/Components/Dashboard/Others/DonationData.json
  app/Components/Dashboard/Others/DonationDetails.jsx
  app/Components/Dashboard/Others/DonationGraph.jsx
  app/Components/Dashboard/Others/DonationList.jsx
  app/Components/Dashboard/Others/Header.jsx
  app/Components/Dashboard/UserDashboard.jsx
  package-lock.json
  package.json
Labels: enhancement, Component, Feature, UI UX

#34 Changed project structure and added navigation to user and the admin dashboards.
  app/AdminDashboard/Campaign/AmountTrendChart.jsx
  app/AdminDashboard/Campaign/CampaignCard.jsx
  app/AdminDashboard/Campaign/CampaignList.jsx
  app/AdminDashboard/page.jsx
  app/Components/Others/NavBar.jsx
  app/UserDashboard/Others/Details.jsx
  app/UserDashboard/Others/DonationData.json
  app/UserDashboard/Others/DonationDetails.jsx
  app/UserDashboard/Others/DonationGraph.jsx
  app/UserDashboard/Others/DonationList.jsx
  app/UserDashboard/Others/Header.jsx
  app/UserDashboard/page.jsx
  app/layout.tsx
  app/page.jsx
Labels: enhancement, Component, Backend

#35 User Dashboard Component Updation
  app/Components/Others/NavBar.jsx
  app/UserDashboard/Others/DonationGraph.jsx
  app/UserDashboard/UserComponents/Data/DonationData.json
  app/UserDashboard/UserComponents/DonationAnalytics.jsx
  app/UserDashboard/UserComponents/DonationHistory.jsx
  app/UserDashboard/UserComponents/DontionDetails.jsx
  app/UserDashboard/UserComponents/Header.jsx
  app/UserDashboard/UserComponents/RewardsAndBadges.jsx
  app/UserDashboard/page.jsx
  package-lock.json
  package.json
Labels: enhancement, Component, Feature, UI UX

#36 Major changes in Login page
  app/Auth/firebase.tsx
  app/Auth/page.jsx
  app/Components/About.jsx
  app/Components/Auth/SignIn.jsx
  app/Components/Features.jsx
  app/Components/Footer.jsx
  app/Components/LearnMore.jsx
  app/Components/Main.jsx
  app/Components/NavBar.jsx
  app/Components/Others/NavBar.jsx
  app/page.jsx
Labels: enhancement, Component, Feature, UI UX, Backend, DataBase

#39 location bug fix
  app/AdminDashboard/Campaign/AmountTrendChart.jsx
  app/AdminDashboard/Campaign/CampaignList.jsx
  app/AdminDashboard/page.jsx
  app/CampaignPage/page.jsx
Labels: bug

#41 Adding the Create Campaign Page
  app/Auth/firebase.tsx
  app/CampaignPage/page.jsx
  app/Components/Main.jsx
  app/Components/NavBar.jsx
  app/CreateCampaign/page.jsx
  package-lock.json
  package.json
Labels: enhancement, Component, Feature, UI UX, Backend, DataBase

#42 Added new components to the admin dashboard and UI overhaul.
  app/AdminDashboard/Campaign/AmountTrendChart.jsx
  app/AdminDashboard/Campaign/CampaignCard.jsx
  app/AdminDashboard/Campaign/CampaignList.jsx
  app/AdminDashboard/Campaign/DonationDistributionBarChart.jsx
  app/AdminDashboard/Campaign/TodaysDonationsCard.jsx
  app/AdminDashboard/Campaign/TopCampaignsCard.jsx
  app/AdminDashboard/Campaign/TotalDonationsCard.jsx
  app/AdminDashboard/page.jsx
  package-lock.json
  package.json
Labels: Component, Feature, UI UX, Backend
