Repository YNVSolutions/SwiftCause_Web, pull requests merged in 2025-08, with the labels that each got.

#60 Integrate Firebase/Firestore for Backend Data
  .gitignore
  README.md
  package-lock.json
  package.json
  src/components/CampaignListScreen.tsx
  src/components/shared/CampaignCard.tsx
  src/lib/firebase.ts
  src/vite-env.d.ts
Labels: enhancement, Component, Backend, DataBase

#62 Fixed the styling issue with tailwind (using Tailwindcss CLI).
  package-lock.json
  package.json
  src/styles/globals.css
Labels: bug

#66 Integrate Firestore, Add Real-Time Editing in Admin Dashboard
  output.css
  package-lock.json
  package.json
  src/App.tsx
  src/components/admin/CampaignManagement.tsx
Labels: enhancement, Component, Backend, DataBase

#67 Resolves the styling issue caused by tailwind integration in the initial setup.
  eslint.config.js
  index.html
  input.css
  output.css
  package-lock.json
  package.json
  public/Camp_setup.png
  public/Flex_Donation_mode.png
  public/Integrated_Comm.png
  public/Real_Time_Funds.png
  public/banner.png
  public/charity.png
  public/demo1.png
  public/demo2.png
  public/demo3.png
  public/demo4.png
  public/demo5.png
  public/demo6.png
  public/demo7.png
  public/demo8.png
  public/gift_aid.png
  public/head_image.png
  public/index.html
  public/manifest.json
  public/mobile_pay.png
  public/robots.txt
  public/swiftcause.jpg
  public/vite.svg
  src/App.css
  src/App.test.tsx
  src/assets/react.svg
  src/components/admin/CampaignManagement.tsx
  src/index.css
  src/logo.svg
  src/main.tsx
  src/react-app-env.d.ts
  src/reportWebVitals.ts
  src/setupTests.ts
  src/vite-env.d.ts
  tailwind.config.js
  tsconfig.app.json
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
Labels: bug, UI UX

#70 Vercel deployment bug fixing
  src/supabase/functions/server/index.tsx
  src/supabase/functions/server/kv_store.tsx
  tsconfig.app.json
Labels: bug

#72 Added backend logic for kiosk login and seeded mock data on firebase.
  package-lock.json
  package.json
  seedKiosk.js
  src/components/KioskLogin.tsx
Labels: Backend, DataBase

#75 Redundant UI deletions
  src/components/AdminLogin.tsx
  src/components/KioskLogin.tsx
  src/components/LoginScreen.tsx
Labels: UI UX

#78 Implement 3-Layer Architecture for Data Handling
  src/api/authService.js
  src/api/firestoreService.js
  src/components/AdminLogin.tsx
  src/components/CampaignListScreen.tsx
  src/components/KioskLogin.tsx
  src/hooks/useAuth.js
  src/hooks/useCampaigns.js
  src/hooks/useKiosks.js
  tsconfig.app.json
Labels: Component, Backend

#89 Campaign Management Feature Enhancement
  src/api/firestoreService.js
  src/api/firestoreService.ts
  src/assets/logo.png
  src/assets/react.svg
  src/components/admin/CampaignManagement.tsx
  src/hooks/useCampaignManagement.ts
  src/hooks/useCampaigns.js
  src/hooks/useCampaigns.ts
  src/lib/firebase.ts
  src/lib/imageUpload.ts
Labels: enhancement, Feature, Backend, DataBase

#94 User management feature
  src/api/donationsApi.ts
  src/api/userApi.ts
  src/components/admin/DonationManagement.tsx
  src/components/admin/UserManagement.tsx
  src/hooks/donationsService.ts
  src/hooks/useUsers.ts
Labels: enhancement, Component, Backend, DataBase

#96 Enhanced Data Rendering & Core Feature Improvements
  src/api/firestoreService.ts
  src/components/LoginScreen.tsx
  src/components/admin/AdminDashboard.tsx
  src/components/admin/DonationManagement.tsx
  src/components/admin/data/mockUserData.ts
  src/components/admin/utils/userManagementHelpers.ts
  src/hooks/useDashboardData.ts
Labels: bug, enhancement, Component, UI UX, Backend, DataBase

#97 Fixed bugs and improved UX for campaign management related screens.
  src/App.tsx
  src/api/firestoreService.ts
  src/components/CampaignScreen.tsx
  src/components/DonationSelectionScreen.tsx
  src/components/admin/AdminDashboard.tsx
  src/components/admin/CampaignManagement.tsx
  src/components/admin/components/CampaignConfigurationDialog.tsx
  src/components/admin/components/KioskCampaignAssignmentDialog.tsx
  src/components/shared/CampaignCard.tsx
  src/features/campaigns/hooks/useCampaignList.ts
  src/hooks/useCampaignManagement.ts
  src/hooks/useCampaigns.ts
Labels: enhancement, Feature, UI UX

#98 Various bug fixes, campaign UI upgrade and gallery Images and other data features addition.
  src/App.tsx
  src/api/firestoreService.ts
  src/components/CampaignListScreen.tsx
  src/components/CampaignScreen.tsx
  src/components/admin/AdminDashboard.tsx
  src/components/admin/CampaignManagement.tsx
  src/components/shared/CampaignCard.tsx
  src/components/shared/UploadButton.tsx
  src/features/campaigns/hooks/useCampaignList.ts
  src/features/payment/hooks/usePayment.ts
  src/hooks/useDashboardData.ts
  src/lib/firebase.ts
Labels: bug, enhancement, UI UX

#100 Feature Enhancements for the Admin Dashboard
  src/components/admin/AdminDashboard.tsx
Labels: enhancement, Component, Feature, UI UX
