Repository YNVSolutions/SwiftCause_Web, pull requests merged in 2025-05, with the labels that each got.

#44 Updated user dashboard
  .github/workflows/push.yml
  app/UserDashboard/Others/Details.jsx
  app/UserDashboard/Others/DonationData.json
  app/UserDashboard/Others/DonationDetails.jsx
  app/UserDashboard/Others/DonationGraph.jsx
  app/UserDashboard/Others/DonationList.jsx
  app/UserDashboard/Others/Header.jsx
  app/UserDashboard/Others/RewardsAndBadges.jsx
  app/UserDashboard/page.jsx
  app/api/create-payment-intent/route.tsx
  package-lock.json
  package.json
Labels: bug, enhancement, Component

#47 Payment gateway integration using stripe
  app/CampaignPage/page.jsx
  app/Components/NavBar.jsx
  app/Payment/Others/CheckoutPage.tsx
  app/Payment/Others/PaymentHeader.jsx
  app/Payment/lib/convertToSubcurrency.tsx
  app/Payment/page.jsx
  app/PaymentSucess/page.tsx
  app/api/create-payment-intent/route.ts
  app/api/create-payment-intent/route.tsx
  package-lock.json
  package.json
Labels: Component, Backend, DataBase, Payment

#45 Changes to admin components and backend logic to facilitate campaign specific admin dashboard.
  app/AdminCampaignDashboard/CampaignSideBar.jsx
  app/AdminCampaignDashboard/page.jsx
  app/AdminDashboard/Campaign/AmountTrendChart.jsx
  app/AdminDashboard/Campaign/CampaignCard.jsx
  app/AdminDashboard/Campaign/TotalDonationsCard.jsx
  app/AdminDashboard/page.jsx
  package-lock.json
  tsconfig.json
Labels: enhancement, Component, Feature, Backend

#54 Fetching and adding more data and adding new buttons to handle the campaign.
  app/AdminCampaignDashboard/page.jsx
  app/AdminDashboard/Campaign/DonationDistributionBarChart.jsx
Labels: Component, Backend, DataBase

#57 User dashboard and Campaign Page firebase integration
  app/CampaignPage/page.jsx
  app/Components/Loader.jsx
  app/CreateCampaign/page.jsx
  app/UserDashboard/Others/Campaigns.jsx
  app/UserDashboard/Others/Details.jsx
  app/UserDashboard/Others/DonationData.json
  app/UserDashboard/Others/DonationDetails.jsx
  app/UserDashboard/Others/DonationDistrbution.jsx
  app/UserDashboard/Others/DonationGraph.jsx
  app/UserDashboard/Others/DonationList.jsx
  app/UserDashboard/Others/DonationTrend.jsx
  app/UserDashboard/Others/Header.jsx
  app/UserDashboard/Others/InfoCard.jsx
  app/UserDashboard/Others/RewardsAndBadges.jsx
  app/UserDashboard/Others/TopCampaigns.jsx
  app/UserDashboard/page.jsx
Labels: enhancement, Component, Feature, UI UX, Backend, DataBase
