Repository YNVSolutions/SwiftCause_Web, pull requests merged in 2025-09, with the labels that each got.

#107 Some ui updates
  src/components/SignupScreen.tsx
Labels: bug

#118 Added currency selection system for the organizations and corresponding payment processing for it.
  src/App.tsx
  src/api/firestoreService.ts
  src/components/CampaignListScreen.tsx
  src/components/CampaignScreen.tsx
  src/components/PaymentScreen.tsx
  src/components/SignupScreen.tsx
  src/components/shared/CampaignCard.tsx
  src/features/auth/hooks/useAdminLogin.ts
  src/features/auth/hooks/useKioskLogin.ts
  src/features/campaigns/hooks/useCampaignList.ts
  src/features/payment/containers/PaymentContainer.tsx
  src/utils/currencyFormatter.ts
Labels: Feature, Backend, DataBase

#116 Implemented a fix to address a bug related to incorrect amount calculations within the Stripe payment gateway
  src/api/authService.js
  src/api/authService.ts
  src/components/admin/AdminDashboard.tsx
  src/components/admin/KioskManagement.tsx
  src/features/payment/hooks/usePayment.ts
Labels: bug, UI UX, Backend, Payment

#121 Adding some enhancements to the application
  src/api/donationsApi.ts
  src/components/CampaignListScreen.tsx
  src/components/admin/AdminDashboard.tsx
  src/components/admin/KioskManagement.tsx
  src/hooks/useKioskPerformance.ts
Labels: bug, enhancement, UI UX, Backend

#130 Implement Admin User Management and Permissions with Firebase Functions
  src/api/userApi.ts
  src/components/admin/UserManagement.tsx
  src/hooks/useUsers.ts
Labels: enhancement, Component, Feature, Backend, DataBase

#132 Enhancements to the Landing Page
  src/components/HomePage.tsx
Labels: enhancement, UI UX

#166 Integrate and Activate Footer CTA Components
  public/aboutSection.png
  public/ourStory.png
  src/App.tsx
  src/components/HomePage.tsx
  src/components/SignupScreen.tsx
  src/components/pages/AboutPage.tsx
  src/components/pages/ContactPage.tsx
  src/components/pages/DocumentationPage.tsx
  src/components/pages/TermsPage.tsx
  src/components/shared/Footer.tsx
Labels: enhancement, Component, Feature, UI UX
